stages:
  get_data:
    cmd: python src/full_pipe/get_data.py
    deps:
    - src/full_pipe/get_data.py
    outs:
    - data/03_part/raw/SeoulBikeData.csv
  prepare:
    cmd: python src/full_pipe/prepare.py data/03_part/raw/SeoulBikeData.csv
    deps:
    - data/03_part/raw/SeoulBikeData.csv
    - src/full_pipe/prepare.py
    outs:
    - data/03_part/processed/test.csv
    - data/03_part/processed/train.csv
  train:
    cmd: python src/full_pipe/train.py data/03_part/processed/train.csv
    deps:
    - data/03_part/processed/train.csv
    - src/full_pipe/train.py
    outs:
    - models/rf_model.pkl
  evaluate:
    cmd: python src/full_pipe/evaluate.py models/rf_model.pkl data/03_part/processed
    deps:
    - data/03_part/processed
    - models/rf_model.pkl
    - src/full_pipe/evaluate.py
    metrics:
    - metrics/metrics.json:
        cache: false
